#!/usr/bin/env bash
# After configuring domain zone, use this script to output where each subdomain points to
digFun () {
    dom=$1
    subdom=$2

    dig "$dom.$subdom" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$dom" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

allSubDom=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 1 ]; then
    url="$1"
    for sub in "${allSubDom[@]}"
    do
	digFun "$sub" "$url"
    done
elif [ $# -eq 2 ]; then
    url="$1"
    sub="$2"
    digFun "$sub" "$url"
fi
