#!/usr/bin/env bash
#configure nginx server to redirect to another page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
