#!/usr/bin/env bash
#configure nginx server to have a custom 404 page
apt-get -y update
apt-get -y install nginx
echo "Hello world!" > /var/www/html/index.html
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx restart
