#!/usr/bin/env bash
#configure nginx server to have a custom 404 page
echo "Hello world!" > /var/www/html/index.html

echo -e "Ceci n'est pas une page\n" > /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx restart
