#!/usr/bin/env bash
# add nginx response header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "/server_name _;/a add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sudo service nginx restart
