#!/usr/bin/env bash
# install and configures HAproxy on the server
# to load balance between two servers

sudo apt-get -y update
sudo apt -y install haproxy
echo "
frontend node-http
    bind *:80
    mode http
    default_backend the_backend
backend the_backend
    balance roundrobin
    option forwardfor
    server 3845-web-01 3.236.18.6:80 check
    server 3845-web-02 44.211.31.225:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
