#!/usr/bin/env bash
# configures ubuntu machine to haproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*
sudo echo "
frontend front
	bind *:80
	default_backend back

backend back
	balance roundrobin
	server 3845-web-01 3.236.18.6 check
	server 3845-web-02 44.211.31.225 check" >>/etc/haproxy/haproxy.cfg
sudo service haproxy restart
