#!/usr/bin/env bash
# install and configures HAproxy on the server
# to load balance between two servers

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*
echo "
frontend node-http
    bind *:80
    mode http
    default_backend theBackend
backend theBackend
    balance roundrobin
    server web-01 3.236.18.6:80 check
    server web-02 44.211.31.225:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
